name: Docker Image Express

on:
  push:
    branches: [ envs ]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: development
    strategy:
      matrix:
        node-version: [ 18.x, 20.x ]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - run: npm ci
    - run: npm test

  deploy:
    runs-on: ubuntu-latest
    environment: development
    needs: [ test ]
    steps:
    - uses: actions/checkout@v4
    - name: Docker build to registry
      env:
        REGISTRY: ${{ secrets.REGISTRY }}
        REPOSITORY: ${{ vars.REPOSITORY }}
        IMAGE_TAG: ${{ github.sha }}
      run: docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .

#  Empty comment to test the workflow























