name: Docker Image Express

on:
  workflow_dispatch:
#  push:
#    branches: [ auth-with-role ]

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    environment: development
    strategy:
      matrix:
        node-version: [ 18.x, 20.x ]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - run: npm ci
    - run: npm test

  build:
    runs-on: ubuntu-latest
    environment: development
    needs: [ test ]
    steps:
    - uses: actions/checkout@v4
    - name: Docker build to registry
      env:
        REGISTRY: ${{ secrets.REGISTRY }}
        REPOSITORY: ${{ vars.REPOSITORY }}
        IMAGE_TAG: ${{ github.sha }}
      run: docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4  # action para configurar las credenciales de AWS
      with:
        role-to-assume: ${{ secrets.AWS_ROLE }}
        aws-region: ${{ vars.AWS_REGION }}
    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v2  # action para iniciar sesión en Amazon ECR

# Comment





















